
networks:
  homelab_homelabnet:
    external: true

services:
  lmstudio:
    image: lmstudio:latest
    container_name: lmstudio
    restart: unless-stopped
    build:
      context: "$HOME/Development/LMStudio"
    ports:
      - "1234:1234"
    volumes:
      - "$HOME/Development/LMStudio/data:/root/.cache/lm-studio/models"
    environment:
      - CONTEXT_LENGTH=${CONTEXT_LENGTH:-131072}
      - MODEL_PATH=${MODEL_PATH:-Qwen/Qwen2.5-Coder-14B-Instruct-GGUF}
      - MODEL_IDENTIFIER=${MODEL_IDENTIFIER:-qwen2.5-coder-14b-instruct}
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    command: ["/start_services.sh"]
    networks:
      - homelab_homelabnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lmstudio.entrypoints=http"
      - "traefik.http.routers.lmstudio.rule=Host(`lmstudio.${DOMAIN}`)"
      - "traefik.http.services.lmstudio.loadbalancer.server.port=1234"